services: 
  multi-company:
    image: bitnami/postgresql
    ports:
     - 5432:5432
    environment:
    - POSTGRESQL_USERNAME=multi-company
    - POSTGRESQL_PASSWORD=multi-company
    - POSTGRESQL_DATABASE=mamulti-companyin